cd file with accounts (inventory)
[redhat]
karalov01 ansible_ssh_user=ec2-user
karalov02 ansible_ssh_user=ec2-user
[ubuntu]
karalov03 ansible_ssh_user=ec2-user ansible ssh_port=2222
---
#adhock:
>ansible redhat -m ping -i inventory
#Install a package
>ansible ubuntu -m apt -a "name=git" -i inventory
>ansible redhat -m yum -a "name=git" -i inventory
#Run a bash command:
                -m command -a "ls"
#Copy a file
				-m copy -a"src=inventory dest="ansible/"

#playbooks
 ---
 - name: install git on Ubuntu
   hosts: ubuntu
   become: True
   tasks:
      - name: install git
	    apt: name=git
		
- name: install git on redhat
   hosts: redhat
   become: True
   vars:
      package: git
   tasks:
      - name: install {{ package }}
	    yum: name="{{ package }}" 
		
ansible-playbook myplaybook.yml -i inventory

#variables.yml
---
package: git

---
- name: install {{ package }}
   hosts: all
   become: True
   vars_files:
     - variables.yml
   tasks:
      - name: update cache on Ubuntu
	    apt:
		  update_cache: True
		when: ansible_os_family == "Debian"

      - name: upgrade Ubuntu
	    apt:
		  upgrade: True
		when: ansible_os_family == "Debian"
		
      - name: install {{ package }} on RedHat
	    yum: name="{{ package }}" state=present
		register: success
		when: ansible_on_family == "RedHat"
	  - debug: var=success
		
		
      - name: install {{ package }} on Ubuntu
	    apt: name="{{ package }}" state=present
		when: ansible_on_family == "Ubuntu"
		gather_facts: False
		
      - name: remove {{ package }} on RedHat
	    yum: 
		   name: "{{ package }}" 
		   state=absent
		when: ansible_on_family == "RedHat"

#--- COMMAND MODULES --
# "shell":
#Use when no existing module or complex requirements (pipes, redirection, grep, awk)
# "command" 
#for simple shell commands, does not support pipes and redirection
# "raw"
#- bypasses the module subsystem
#- used when python in not installed on remote system (Windows)
#- systems with old python (<2.4)
#- network devices (routers, switches)

tasks:
  - name: see network configuration
    shell: ifconfig | grep ens33
    args:
     executable: /bin/bash
    register: net_config
  - debug: var=net_config
   
  - name: copy custom script
    copy:
       src: hello.py
       dest: ~/Desktop	   

  - name: run the script
    command: hello.py
    args:
       chdir: /home/ec2-user/Desktop

  - name: run the script
    raw: bash /home/ec2-user/Desktop/hello.py
 
 
 #--- FILE MODULE -- 
 - name: using file
   hosts: all
   gather_facts: False
   tasks:
     - name: create a directory
       file:
         path: /home/ec2-user/ansible
         state: directory
     - name: create a file
       file:
         path: /home/ec2-user/ansible/hello.txt
         state: touch         
      - name: create a symbolic link
        file:
          src: /home/ec2-user/ansible/hello.txt
          dest: /home/ec2-user/ansible/hello.txt
          state: link           
      - name: delete all
        file:
          path: /home/ec2-user/ansible
          state: absent
# -- FILE MANIPULATIONS/UPDATES -- 
- name: File operations
  hosts: all
  gather_facts: False
  tasks:
    - name: insert text in the end of the file
      lineinfile:
        path: /home/ec2-user/ansible/hello.txt
        line: Hello mummy!
    - name: insert text after specific line
      lineinfile:
        path: /home/ec2-user/ansible/hello.txt
        line: I love you
        insertafter: Hello mummy!
    - name: insert block
      blockinfile:
        path: /home/ec2-user/ansible/hello.txt
        block: |
          Hello my dear friend!
          I want you to be happy
    - name: replace string 
      replace:
        path: /home/ec2-user/ansible/hello.txt
        regexp: be happy
        replace: help me

# Repositories:
# Debian: /etc/apt/sources.list
# Custom repositories: /etc/apt/sourcses.list.d/docker.list
# Yum (redHat)
# /etc/yum.conf
# Extra(custom) under /etc/yum.repos.d/<package>.repo
# Below playbook installs docker
# varfile docker_vars.yml
---
ubuntu_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
redhat_packages:
  - lvm2
  - device-mapper-persistent-data
  - yum-utils

#playbook:
---
- name: install ELK stack
  hosts: all
  become: True
  vars_files:
      - docker_vars.yml
  tasks:
    - name: install ubuntu packages
      apt:
        name: "{{ ubuntu_packages }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: install redhat packages
      yum:
        name: "{{ redhat_packages }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: add Ubuntu GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: add docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        filename: docker
      when: ansible_os_family == "Debian"

    - name: add docker repo for RedHat
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker.repo 
      when: ansible_os_family == "RedHat"

    - name: update caches for ubuntu
      apt:
         update_cache: yes
      when: ansible_os_family == "Debian"

    - name: update caches for redhat
      yum:
        name: "*"
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: install docker on ubuntu
      apt:
        name: docker-ce
        state: present
      when: ansible_os_family == "Debian"

    - name: install docker on radhat
      yum:
        name: docker-ce
        state: present
      when: ansible_os_family == "RedHat"

#Below playbook will install docker containers elastic search, logstash, kibana
---
- name: install python packages
  hosts: all
  become: True
  tasks:

  - name: setup elastic search
    docker_container:
      name: elasticsearch
      state: started
      image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
      exposed_ports:
        - 9200:9200

  - name: setup Logstash
    docker_container:
      name: logstash
      state: started
      image: docker.elastic.co/logstash/logstash:6.3.0
      exposed_ports:
        - 5044:5044
      links:
        - elasticsearch

  - name: setup Kibana
    docker_container:
      name: kibana
      state: started
      image: docker.elastic.co/kibana/kibana:6.3.0
      links:
        - elasticsearch
      exposed_ports:
        - 5061:5061

# Templates
---
- name: configure network
  hosts: all
  become: True
  tasks:

  - name: configure Ubuntu
    template:
      src: ubuntu_net_config.j2
      dest: /etc/network/interfaces
    when: ansible_os_family == "Debian"

# INCLUDE
# main definitions( hosts, vars, become - in main yml, tasks in include yml files
- name: Setup ELK stack
  hosts: all
  become: True
  vars_files:
    - variable.yml
  tasks:
    - include_tasks: install_docker.yml
    - include_tasks: elk_stask.yml

# ROLES
dimitryk@dimitry:~/ansible$ mkdir roles
dimitryk@dimitry:~/ansible$ cd roles
dimitryk@dimitry:~/ansible/roles$ ansible-galaxy init docker
dimitryk@dimitry:~/ansible/roles$ cd docker
dimitryk@dimitry:~/ansible/roles/docker$ ls
defaults  files  handlers  meta  README.md  tasks  templates  tests  vars

# defaults: for default variables
# vars: overwrite default vars
# tasks: yml file with tasks list
---
- name: Setup ELK stack
  hosts: all
  become: true
  roles:
    - role: docker
    - role: elkstack

---
- name: Build and deploy AWX
  hosts: all
  gather_facts: false
  roles:
    - { role: check_vars }
    - { role: image_build, when: "dockerhub_base is not defined" }
    - { role: image_push, when: "docker_registry is defined and dockerhub_base is not defined" }
    - { role: kubernetes, when: "openshift_host is defined or kubernetes_context is defined" }
    - { role: local_docker, when: "openshift_host is not defined and kubernetes_context is not defined" }


# CHECK VARIABLES:
#check_docker.yml
---
- name: postgres_data_dir should be defined
  assert:
    that:
    - postgres_data_dir is defined and postgres_data_dir != ''
    msg: "Set the value of 'postgres_data_dir' in the inventory file."
  when: pg_hostname is not defined or pg_hostname == ''

- name: host_port should be defined
  assert:
    that:
    - host_port is defined and host_port != ''
    msg: "Set the value of 'host_port' in the inventory file."

#REGISTER
tasks: 
- name: Record Uptime
  shell: /usr/bin/uptime
  register: result

- name: Display Uptime
  debug: msg="{{ result.stdout }}"
  
#AWX
git clone https://github.com/ansible/awx

#JINJA2
{% for switch ion config -%}
hostname {{ switch.switch_hostname }}
  {# "dictsort" automatically creates an iterator for us #}
  {% for id,name in switch.vlans|dictsort %}
       vlan {{ id }}
       name {{ name }}
   {% endfor }}
{% endfor %}

# config.yml :
---
- switch_hostname: sw01
  vlans:
    10: Management
    20: vMotion
    30: Server Network 1
    40: Server Network 2

- switch_hostname: sw02
  vlans:
    10: Management
    20: vMotion
    30: Server Network 1
    40: Server Network 2

- switch_hostname: sw03
  vlans:
    210: Marketing
    220: Sales
    230: Finance

#include
{% include "4-advobjects.j2" %}
There were {{ config| length }} switches in this configuration.

#inline vars
{% set TESTVAR = config['message'] %}
{{ TESTVAR }}
{% set TESTVAR = 'Hello' %}
{{ TESTVAR }}


#dynamic var file, handlers using roles
---
- include_vars: "{{ ansible_os_family }}.yml"
- name: Main routing config file
  template: src={{ conftamplate }} dest={{ conffile }}
  notify: Apply sysctl changes  # - will call handler with name Apply sysctl changes, only when success

#Handler main.yml (under handlers folder)
---
- name: Apply sysctl changes
  shell: sudo sysctl -p {{ conffile }}

#Var files under vars folder
#Debian.yml
---
conftemplate: 'roles/router/templates/sysctl.conf.j2'
conffile: '/etc/sysctl.conf'
testvar: 'Hello WOrld'
